name : gonzag
channels:
  - conda-forge
dependencies:
  - python=3.9.2
  - numpy=1.20.1
  - pandas=1.2.3
  - xarray=0.17.0
  - dask=2021.3.0
  - distributed=2021.3.0
  - netcdf4=1.5.6
  - zarr=2.6.1
  - jupyter=1.0.0
  - ipykernel=5.3.4
  - dask-jobqueue=0.7.1
  - matplotlib=3.3.4
  - shapely=1.7.1
  - scipy=1.6.2
